/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edamatec_project.views;

import edamatec_project.dao.ClienteDAO;
import edamatec_project.models.Cliente;
import java.util.List;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class Clientes_View extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Clientes_View(String filtroCampo, String filtroTexto) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (UnsupportedLookAndFeelException e) {
            // handle exception
        } catch (ClassNotFoundException e) {
            // handle exception
        } catch (InstantiationException e) {
            // handle exception
        } catch (IllegalAccessException e) {
            // handle exception
        }
        initComponents();
        boxFiltro.setSelectedItem(filtroCampo);
        jTextFieldFiltro.setText(filtroTexto);
        
        ClienteDAO clienteDAO = new ClienteDAO();
        List<Cliente> clientes = clienteDAO.find(filtroCampo, filtroTexto);

        DefaultTableModel tbModel = (DefaultTableModel) JTable_Clientes.getModel();

        String data[] = new String[5];

        for (int i = 0; i < clientes.size(); i++) {
            data[0] = String.valueOf(clientes.get(i).getId());
            data[1] = clientes.get(i).getCpf();
            data[2] = clientes.get(i).getNome();
            data[3] = clientes.get(i).getTelefone();
            data[4] = clientes.get(i).getEmail();

            tbModel.addRow(data);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        JButton_Novo_Cliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_Clientes = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        boxFiltro = new javax.swing.JComboBox<>();
        jTextFieldFiltro = new javax.swing.JTextField();
        jButtonLupa = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 51, 153));
        setPreferredSize(new java.awt.Dimension(648, 483));

        JButton_Novo_Cliente.setText("Novo Cliente");
        JButton_Novo_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_Novo_ClienteActionPerformed(evt);
            }
        });

        JTable_Clientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JTable_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF", "Nome", "Telefone", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable_Clientes);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        boxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "nome", "email", "cpf", "telefone" }));

        jButtonLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edamatec_project/images/icon_lupa.png"))); // NOI18N
        jButtonLupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLupaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditar)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluir)
                .addGap(18, 18, 18)
                .addComponent(JButton_Novo_Cliente)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JButton_Novo_Cliente)
                        .addComponent(jButtonExcluir)
                        .addComponent(jButtonEditar)
                        .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_Novo_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_Novo_ClienteActionPerformed
        // TODO add your handling code here:
        ERP_View.showView(new Novo_Cliente_View());
    }//GEN-LAST:event_JButton_Novo_ClienteActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        if (JTable_Clientes.getSelectedRow() > -1) {
            // print first column value from selected row
            int idSelected = Integer.parseInt(JTable_Clientes.getValueAt(JTable_Clientes.getSelectedRow(), 0).toString());
            ClienteDAO clienteDAO = new ClienteDAO();
            if (clienteDAO.destroy(idSelected)) {
                ERP_View.showView(new Clientes_View("all", null));
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        if (JTable_Clientes.getSelectedRow() > -1) {
            // print first column value from selected row
            Cliente cliente = new Cliente();
            cliente.setId(Integer.valueOf(JTable_Clientes.getValueAt(JTable_Clientes.getSelectedRow(), 0).toString()));  
            cliente.setCpf(JTable_Clientes.getValueAt(JTable_Clientes.getSelectedRow(), 1).toString());
            cliente.setNome(JTable_Clientes.getValueAt(JTable_Clientes.getSelectedRow(), 2).toString());
            cliente.setTelefone(JTable_Clientes.getValueAt(JTable_Clientes.getSelectedRow(), 3).toString());
            cliente.setEmail(JTable_Clientes.getValueAt(JTable_Clientes.getSelectedRow(), 4).toString());
            
            ERP_View.showView(new Cliente_View(cliente));
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonLupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLupaActionPerformed
        // TODO add your handling code here:
        String filtroCampo = String.valueOf(boxFiltro.getSelectedItem());
        String filtroTexto = String.valueOf(jTextFieldFiltro.getText());
        
        ERP_View.showView(new Clientes_View(filtroCampo,filtroTexto));
    }//GEN-LAST:event_jButtonLupaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_Novo_Cliente;
    private javax.swing.JTable JTable_Clientes;
    private javax.swing.JComboBox<String> boxFiltro;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLupa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextFieldFiltro;
    // End of variables declaration//GEN-END:variables
}
